

#create zone for proxy cache, save static files
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;


upstream nextjs_upstream {
    hash $remote_addr consistent;
    server 127.0.0.1:3000;
    # recommended keep alive value to be double the amount of servers
    keepalive 2;
}

upstream nodejs_upstream {
    hash $remote_addr consistent;
    server 127.0.0.1:8080;
    # recommended keep alive value to be double the amount of servers
    keepalive 2;
}


server {
    # nginx listening on port 80
        listen 80;

        server_name localhost;
        gzip on; 
        gzip_proxied any;
        gzip_comp_level 4;
        gzip_types text/css application/javascript image/svg+xml; 

        server_tokens off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

         # Serve static files 
         location / {         
        
            proxy_pass http://nextjs_upstream;  
        }

        # Proxy /api requests to nodejs server
        location /api {
            proxy_pass http://nodejs_upstream;
        }

        # Cache next.js built assets such as javascropt bundles here
        location /_next/static {
         proxy_cache STATIC;
         proxy_pass http://nextjs_upstream;

        # For testing cache - remove before   deploying to production
        # add_header X-Cache-Status $upstream_cache_status;
  }
        
        # Cache other static assets such as images here
        location /static {
            proxy_cache STATIC;
            # avoid using outdated data
             proxy_ignore_headers Cache-Control;
             proxy_cache_valid 60m;
            proxy_pass http://nextjs_upstream;

            # for testing, remove later
            # add_header X-Cache-Status $upstream_cache_status;
        }    

}


